# Generated by Django 5.0.7 on 2024-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.AddField(
            model_name='user',
            name='key_generates',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
