# Generated by Django 5.0.7 on 2024-08-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_remove_product_is_commanded_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
