# Generated by Django 5.1 on 2024-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_checkoutsessionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CheckoutSessionRecord',
        ),
    ]
