# Generated by Django 5.1 on 2024-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_generate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
