# Generated by Django 5.1 on 2024-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_user_key_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key_generate_order',
            field=models.CharField(default='', max_length=200),
        ),
    ]
